#! /usr/bin/python
from pythonlib.swarm import Swarm
import sys
import getopt
#--------------------------------------------------------------------------------------------------------------------------
# Author: Szech696
# Desciption: SWARM is a bruteforce utility for HTML login forms. 
# The speed of SWARM greatly depends upon how fast your connection/computer are. The better the processor the faster, and
# more (if specified) threads SWARM executes. The quicker your connection, the faster POST requests can be made.
# -------------------------------------------------------------------------------------------------------------------------
# THIS IS FOR EDUCATION OR RESEARCH USE ONLY. AUTHOR DOES NOT CONDONE ANY USE FOR ATTEMPT TO GAIN UNAUTHORIZED ACCESS TO 
# SOMEONE ELSES ACCOUNT and/or PROPERTY. DO NOT USE ON A DOMAIN/PROPERTY THAT DOES NOT BELONG TO YOU, OR YOU DO NOT HAVE PERMISSION TO DO SO!
# USE AT YOUR OWN RISK!! AND ABOVE ALL ELSE - ENJOY ;)
#--------------------------------------------------------------------------------------------------------------------------


# function: usage
# description: Displays Example message and exits
def usage():
	print('Usage:')
	print('\t'+sys.argv[0] + ' %s %s %s '%('--url=http://example.com/login.php',
			'--user-file=usernames.txt',
			'--pass-file=passwords.txt'))
	sys.exit()

# function: help
# description: Displays the help message and exits
def showhelp():
	print('\t--url=<ARGUMENT>			The URL where the login form is located')
        print('\t--username=<ARGUMENT>			Use a specific username for each attempt (overrides --user-file option)')
        print('\t--user-file=<ARGUMENT>			The username file to use with swarm')
        print('\t--pass-file=<ARGUMENT>			The password file to use with swarm')
        print('\t--threads=<ARGUMENT>			The number of threads to run swarm with. NOTE depending on the CPU, to many threads can hurt performance')
        print('\t--verbose				Verbose output')
	print('\t--update-time=<ARGUMENT>		Total time in seconds between showing statistics')
        print('\t--tor					Use tor with swarm')
        print('\t--check-tor				To confirm you are using TOR before swarm continues.')
        print('\t--sql-inject				Try to bypass login with SQL Injections.')
        print('\t--crawl=<ARGUMENT>			Crawls the domain for login forms')
	usage()

# function: main
# param: argv		- System arguments
# description: Main function of swarm
def main(argv):
	swarm = None
	target = None
	username = None
	usernameFile = None
	passwordFile = None
	threads = 1
	verbose = False
	updateTime = None
	checkTor = False	
	tor = False
	sqlInject = False
	crawl = False
	depth = None
	try:
		opts, args = getopt.getopt(argv[1:],'' ,['help',
							 'url=',
							 'user-file=',
							 'pass-file=',
							 'threads=',
							 'verbose',
							 'update-time=',
							 'tor',
							 'check-tor', 
							 'username=',
							 'sql-inject',
							 'crawl='])	
	# Invalid Option
	except getopt.GetoptError as err:
		print(str(err))
		usage()

	for opt, arg in opts:
		if opt == '--help':
			showhelp()
		if opt == '--url':
			target = arg	
		if opt == '--username':
			username = arg	
		if opt == '--user-file':
			usernameFile = arg	
		if opt == '--pass-file':
			passwordFile = arg	
		if opt == '--threads':
			threads = int(arg)	
		if opt == '--verbose':
			verbose = True	
		if opt == '--update-time':
			updateTime = int(arg)	
		if opt == '--check-tor':
			checkTor = True	
		if opt == '--tor':
			tor = True	
		if opt == '--sql-inject':
			sqlInject = True	
		if opt == '--crawl':
			crawl = True	
			depth = int(arg)

	swarm = Swarm(username,usernameFile,passwordFile,target,threads,verbose,tor,checkTor,sqlInject,crawl,depth,updateTime)
	if crawl:
		swarm.startCrawling()
	else:
		swarm.startBruteforcing()
if __name__ == "__main__":
	main(sys.argv)
